github:
  description: "A tool for working with Apache Sling content packages"
  labels:
  - "sling"
  - "javascript"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
